### ISSUE TITLE
Katselmoidaan mihin Swaggeria voisi käyttää.

### ISSUE THREAD

**Issue by jaakkokorhonen** [omahoito/rfc#30]

**Comment by vlindhol** [comment]
Done in #39, seems like a pretty good standard. Key points:

* Quite well thought out, especially for REST + JSON APIs.
* Swagger 2.0 is now being transformed into the [Open API Specification](https://github.com/OAI/OpenAPI-Specification), which hints at wide adoption. Looks like the 3.0 release for OpenAPI is coming soon (release candidates are already out).
* When describing JSON objects, Swagger uses a subset of the JSON Schema format. There are some issues that makes describing FHIR resources difficult (lack of support for recursion, lack of the `oneOf`keyword) but this seems to be fixed in OpenAPI 3.0.
* The Swagger/OpenAPI description file must be rendered e.g. by the Swagger Editor or the tool swagger-ui, which requires hosting. At the moment it's a bit of a pain to set up swagger-ui locally.

Conclusion: Swagger 2.0 is mostly fine to use, and can easily be migrated to the OpenAPI Specification 3.0. If we adopt Swagger/OpenAPI more widely, we need to set up some place that runs swagger-ui so that we can actually look at the rendered API descriptions.

**Comment by jaakkokorhonen** [comment]
@jokimaki where do you think we could run Swagger?

**Comment by jokimaki** [comment]
@jaakkokorhonen https://apinf.io/ seems to support Swagger. If we want out own instance of Swagger UI, any hosting provider that supports Node.js or Docker will do. For an immediate temporary setup we could use our CI server as it has Node 6.x already installed.

**Comment by vlindhol** [comment]
Put it on the api test server for easy access: https://oda-test.ebmedscloud.org/api/v1/

In the link above the version of the swagger file is the dev version, i.e. it may not be in sync with the file in this repo.

**Comment by vlindhol** [comment]
Swagger katselmoitu ja käytetty, jatketaan sen käyttöä kyllä.
